### ISSUE TITLE
Allow fetching of metadata from MetaDB

### ISSUE THREAD

**Issue by MeijeSibbel** [lukechampine/us#102]
Summary from Discord;

We need everything stored in MetaDB. Chunk and Shard mean DBChunk and DBShard in this file https://github.com/lukechampine/us/blob/kv/renter/renterutil/metadb.go

Edit: we need this for migration and file sharing purposes.

**Comment by jkawamoto** [comment]
We have [ReadMetafile](https://github.com/storewise/s3-gateway/blob/044ccf4911255acae1974828b39a35d3d41b1509/pkg/meta/metadb.go#L342) and [WriteMetafile](https://github.com/storewise/s3-gateway/blob/044ccf4911255acae1974828b39a35d3d41b1509/pkg/meta/metadb.go#L390), so this mighe be fine.
However, we should make sure if sharing metadata works.

**Comment by lukechampine** [comment]
`MetaDB` is an interface, so in theory you should already have the tools you need: you can create a type that implements `MetaDB` while allowing for import/export. However, you will need to handle some tricky things, like collisions between existing keys (i.e. user A has a blob named "foo", then imports a file named "foo" from user B).

**Comment by jkawamoto** [comment]
We only need the newest blobs, and if I'm not mistaken, it would work with the current implementation for upload/download.
Would migration update the timestamp correctly? For example, after modifying some chunks, it would need to update the timestamp of the parent blob.

**Comment by jkawamoto** [comment]
I found a problem. These two functions use chunk ID and shard ID to calculate something.

https://github.com/lukechampine/us/blob/8a2eb347750d906fe1a10811caef12271df28073/renter/renterutil/metadb.go#L29

https://github.com/lukechampine/us/blob/8a2eb347750d906fe1a10811caef12271df28073/renter/renterutil/metadb.go#L40

However, if we transfer metadata to another client, those IDs won't be identical between clients because they are internally calculated and we cannot modify them. As a result, receivers fail to decrypt data.

**Comment by jkawamoto** [comment]
From the discussion on Discord, we need to store derive nonces in `DBShard`. 
https://discordapp.com/channels/@me/624516039342030848/753449290747215912

**Comment by lukechampine** [comment]
[Nonces are now stored per-shard](https://github.com/lukechampine/us/commit/289e2b3f9c1bfadfa121cf85c0c3e5074d77ded4), so filesharing should work now.
