### ISSUE TITLE
Download panics

### ISSUE THREAD

**Issue by jkawamoto** [lukechampine/us#109]
While downloading a file with PseudoKV, we got this panic:

```go
panic: runtime error: index out of range [2] with length 2

goroutine 612 [running]:
lukechampine.com/us/renter/proto.updateRevisionOutputs(0xc0007e9650, 0xc0007e9500, 0x0, 0x0, 0x0, 0x19e40ad599183100, 0x0, 0x0, 0x0, 0x71870fbd3cd0b366, ...)
        /Users/junpei/src/github.com/lukechampine/us/renter/proto/session.go:833 +0xba3
lukechampine.com/us/renter/proto.(*Session).Read(0xc0008ccb00, 0x2023680, 0xc0005460a0, 0xc0006a4150, 0x1, 0x1, 0x1, 0x1)
        /Users/junpei/src/github.com/lukechampine/us/renter/proto/session.go:416 +0x775
lukechampine.com/us/renter.(*ShardDownloader).CopySection(0xc0007e9c78, 0x20211e0, 0xc00071e0c0, 0x0, 0x400000, 0x40d2b582742052e2, 0xb9de6536c67d6198)
        /Users/junpei/src/github.com/lukechampine/us/renter/download.go:123 +0x146
lukechampine.com/us/renter/renterutil.SerialChunkDownloader.DownloadChunk(0xc000d59000, 0x204a3c0, 0xc000010578, 0x12fe, 0xc0006bea00, 0x14, 0x14, 0x5, 0x1400000, 0xf7cde801643e050e, ...)
        /Users/junpei/src/github.com/lukechampine/us/renter/renterutil/strategies.go:376 +0x54b
lukechampine.com/us/renter/renterutil.ParallelBlobDownloader.DownloadBlob.func1(0xc000612250, 0xc000548780, 0x20236e0, 0xc0000105a8, 0x3, 0x204a3c0, 0xc000010578, 0xc0002b2460, 0xc0005488a0)
        /Users/junpei/src/github.com/lukechampine/us/renter/renterutil/strategies.go:815 +0x20a
created by lukechampine.com/us/renter/renterutil.ParallelBlobDownloader.DownloadBlob
        /Users/junpei/src/github.com/lukechampine/us/renter/renterutil/strategies.go:812 +0x1e1
exit status 2
```

Related to #67.

**Comment by lukechampine** [comment]
I'm not sure how this could occur, since the renter always creates contracts with 3 missed outputs, and when it receives revisions from the host, it verifies their signature. Is this reproducible? If so, can you try running with `-race`?

It also looks like the line numbers are different. Can you share your `session.go`?

**Comment by jkawamoto** [comment]
Here is my session.go https://github.com/jkawamoto/us/blob/kv/renter/proto/session.go

**Comment by jkawamoto** [comment]
Since I couldn't reproduce this recently and we migrated to ParallelChunkDownloader, I'd close this issue.

**Comment by jkawamoto** [comment]
We got another panic with ParallelChunkDownloader:

```go
panic: runtime error: index out of range [2] with length 2 

goroutine 9496 [running]: 
lukechampine.com/us/renter/proto.updateRevisionOutputs(0xc0012098c0, 0xc001209700, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x91a275ec679d3ac3, ...)
  /Users/junpei/src/github.com/lukechampine/us/renter/proto/session.go:833 +0xb46 
lukechampine.com/us/renter/proto.(*Session).Read(0xc0019af080, 0x1447fe0, 0xc00032f040, 0xc001278000, 0x1, 0x1, 0x1, 0x1)
  /Users/junpei/src/github.com/lukechampine/us/renter/proto/session.go:416 +0x7ae 
lukechampine.com/us/renter.(*ShardDownloader).CopySection(0xc001995eb0, 0x1445e60, 0xc00265e090, 0x0, 0x340, 0x8b56b412dd6c63d, 0xe768129e55c21b48) 
  /Users/junpei/src/github.com/lukechampine/us/renter/download.go:123 +0x14f 
lukechampine.com/us/renter/renterutil.ParallelChunkDownloader.DownloadChunk.func1(0xc0008415f0, 0xc001bce000, 0x146dec0, 0xc0006e7090, 0x17e, 0xc002395c20, 0x14, 0x14, 0x5, 0x1002, ...) 
  /Users/junpei/src/github.com/lukechampine/us/renter/renterutil/strategies.go:492 +0x4b0 
created by lukechampine.com/us/renter/renterutil.ParallelChunkDownloader.DownloadChunk 
  /Users/junpei/src/github.com/lukechampine/us/renter/renterutil/strategies.go:465 +0x488
```

**Comment by jkawamoto** [comment]
I'm curious if adding this to `updateRevisionOutputs` solves this problem:
```go
if len(rev.NewMissedProofOutputs) < 3 {
	rev.NewMissedProofOutputs = append(rev.NewMissedProofOutputs, types.SiacoinOutput{})
}
```

**Comment by lukechampine** [comment]
oho, I think I may know what's going on.

The panic occurs because the renter is trying to update the third output of the file contract -- the void output -- but the contract only has two missed outputs. How could this occur? Well, when a contract is renewed, the `RenewAndClear` RPC creates a final revision of the previous contract, and in this final revision, the valid and missed outputs are the same: there is no void output!

So what I *Think* is happening here is that you're `RenewAndClear`-ing a contract, and then attempting to use that contract. When you `Lock` the contract, the host gives you the final revision, which you then attempt to revise. So the fix is simple: the renter should detect contracts that are no longer revisable, and return an error when you attempt to use them.

**Comment by lukechampine** [comment]
wait a minute, I fixed that though; it was fixed in https://github.com/lukechampine/us/pull/42/commits/412755eaf9a54671a1569f15f20641c8c25b8ef1. Are you definitely running that code?

**Comment by jkawamoto** [comment]
Which code do you mean? To avoid panic, I'm testing this https://github.com/lukechampine/us/issues/109#issuecomment-685948084.

Btw, if contract renewal succeeded, I thought the host should return the newest one when trying to lock. How can we get the renewed revision?

**Comment by lukechampine** [comment]
sorry, I mean the code in  412755e, specifically:
```go
	if s.rev.Revision.NewRevisionNumber == math.MaxUint64 {
		return ErrContractFinalized
	}
```
I suspect that, if you do avoid the panic using your `if` check, the host will still reject the revision. That's much better than a panic, of course, but I'm not seeing why this state should occur in the first place. Can you print out the revision number inside your `if` statement? i.e.:
```go
if len(rev.NewMissedProofOutputs) < 3 {
	println("revision number:", rev.NewRevisionNumber)
	rev.NewMissedProofOutputs = append(rev.NewMissedProofOutputs, types.SiacoinOutput{})
}
```

**Comment by jkawamoto** [comment]
Got it. Added the print line.

**Comment by jkawamoto** [comment]
Okay, we got some `revision number: 18446744073709551615` but most of the cases it said `revision number: 0`.

**Comment by lukechampine** [comment]
ok. It looks like the revision number is incremented in most RPCs prior to calling `updateRevisionOutputs`, but not in `Write`. So if the revision number starts at the maximum (18446744073709551615), then `updateRevisionOutputs` will print 18446744073709551615 if called from `Write`, and 0 if called from any other RPC.

I've pushed [a commit](https://github.com/lukechampine/us/commit/500ff65cb1b932f2a9c251924f7e11f9d50b0a91) that checks for finalized contracts before attempting each RPC. I still don't really understand why this is happening, but this should at least turn the panic into an error. And I suppose this check is necessary anyway, since in theory you could revise a contract 18446744073709551615 times. 😅

**Comment by jkawamoto** [comment]
I'm trying out 500ff65cb1b932f2a9c251924f7e11f9d50b0a91 but `RenewAndClearContract` was removed in #116. So, I could update only `session.go`. I hope that's fine, though.

**Comment by lukechampine** [comment]
yeah, unfortunately there is a bit of divergence between `master` and `kv`. I should cherry-pick any commits from `kv` that aren't explicitly KV-related into `master`, then rebase `kv` on top of that.

**Comment by jkawamoto** [comment]
I have another question. If we get "Lock: contract cannot be revised further", can we do anything with this contract?

I'm also not sure why it happens. I think one possible cause is the metadata server accidentally loses a renewed contract and tries to use the old one. Can we renew the old contract again?

**Comment by lukechampine** [comment]
I think the most likely explanation is:

- You have a `HostSet` that's initialized with contract A on host H, but you don't currently have a session with H
- Another process renews A->B, causing A to be finalized
- You upload/download a file using the `HostSet`, causing it to open a session with H
- The session locks contract A, which cannot be revised further

If you get `ErrContractFinalized`, you'll need to recreate the `HostSet` using the renewed contract. You won't be able to renew the old contract again, because the old contract will have been finalized -- it will have no funds left and its revision number will be set to the maximum.

**Comment by jkawamoto** [comment]
Thank you for the explanation! I'll check if there is a race condition with host sets.

Since the panic is fixed, I'll close this issue.
