### ISSUE TITLE
RenewContract: ReadResponse: consensus conflict: provided transaction set is standalone and invalid: transaction cannot have an output or payout that has zero value

### ISSUE THREAD

**Issue by jkawamoto** [lukechampine/us#125]
Many contract renewals fail with this error. Is this something we can avoid in renter-side?

**Comment by lukechampine** [comment]
Hmm. I believe this bug occurs when the host is asked to contribute 0 SC to the contract. Instead of doing nothing, the host adds an output worth 0 SC, which is invalid.

This *should* be mitigated [here](https://github.com/lukechampine/us/blob/master/renter/proto/renew.go#L69-L77). The only thing I can think of is that `MaxCollateral` could be zero, in which case the `IsZero` branch wouldn't trigger (because it's an else-if). You'd end up getting an error in that case anyway, though, since your collateral would exceed `MaxCollateral`.

Are multiple hosts returning this error, or just one?

**Comment by jkawamoto** [comment]
Looks like it happens with only this host:
- [ed25519:235b6bf2fcd0d3e7a9949d6b9a770b02d1665ba32ff6e378174ab89004730a19
](https://siastats.info/hosts?=1223)

![2020-09-08](https://user-images.githubusercontent.com/1793096/92442447-e72e5200-f17d-11ea-8266-4fa1082348dc.png)

**Comment by jkawamoto** [comment]
We get this error with other hosts:
- [ed25519:9a6f3f7cf66637b53ff9027e48419f3f5f5b3c04495928ee0202ac187e8b7ad1](https://siastats.info/hosts?=1242)
- [ed25519:babd59be06b2055f68a6d6999746f3b20abd5836015d96342300c3c2faa6830e](https://siastats.info/hosts?=1817)

Is there any way to solve it, or we cannot renew those contracts?

**Comment by lukechampine** [comment]
You could try running this patch:
```diff
diff --git a/renter/proto/formcontract.go b/renter/proto/formcontract.go
index 0cbe034..9c53ada 100644
--- a/renter/proto/formcontract.go
+++ b/renter/proto/formcontract.go
@@ -78,7 +78,8 @@ func (s *Session) FormContract(w Wallet, tpool TransactionPool, key ed25519.Priv
        // side bug) it can't be zero either.
        if hostCollateral.Cmp(s.host.MaxCollateral) > 0 {
                hostCollateral = s.host.MaxCollateral
-       } else if hostCollateral.IsZero() {
+       }
+       if hostCollateral.IsZero() {
                hostCollateral = types.NewCurrency64(1)
        }
 
```
this should force the collateral to never be 0. My suspicion is that you will get a different error instead, but it's worth a try.

**Comment by jkawamoto** [comment]
With the above patch, we get "RenewContract: ReadResponse: internal error: file contract proposal expects the host to pay more than the maximum allowed collateral".

**Comment by lukechampine** [comment]
ok, it's as I suspected -- the host's `MaxCollateral` is set to 0.

I will submit a patch to fix the host bug, but until people upgrade, renewing the contract is impossible.

**Comment by jkawamoto** [comment]
Thanks for the MR. I hope that it will be merged and published soon.
