### ISSUE TITLE
Download caching (PseudoKV)

### ISSUE THREAD

**Issue by MeijeSibbel** [lukechampine/us#78]
Storing sectors in a download cache will allow the renter to download the chunks once and extract the small files from within the downloaded sectors without having to do multiple requests to the hosts. One of the the challenges is to figure out how much buffer size is required due to potential non-sequential downloads spanning multiple chunks. 
Although caching has to be supported in `us` first, the `gateway` implementation could expose an option `--cache=<bytes>` to allow the operator to manually specify a cache size depending on the available resources. With many enterprise moving to flash based storage solutions sitting between the application and disk-drives, this cache could be stored on the flash arrays and subsequently written to disk.
Download caching will enable higher performance when it comes to handling small files.

**Comment by lukechampine** [comment]
>When downloading a file, the gateway downloads x10 4 MB sectors (40 MB total) every time for all files < 4 MB, even if the file is 1 Byte in size.

This is not true, at least of `us` itself (not sure about your gateway code). Retrieving a 1 byte file requires downloading a total of 64*min_hosts bytes, so 640B in your case. (64 bytes is the "minimum retrievable unit" due to how our Merkle proofs are constructed.) If you are observing otherwise in your tests, I can try to help figure out why you're downloading more than necessary.

There *is* still a potential speedup to be gained by caching, though. If you are storing a bunch of small files within 1 sector, and you *know* that you want to download all of them, then it will be more efficient to issue a single download request for the entire sector, rather than a separate request per file. I think this is out-of-scope for `PseudoFS`, but I will look into it for `PseudoKV`.

**Comment by MeijeSibbel** [comment]
Shoot, sorry about that, i didn't know this wasn't a limitation. @jkawamoto can we check if we're doing things incorrectly per Luke's comment above? If so let's troubleshoot.

Since this is indeed out of scope for `PseudoFS` and mostly geared towards `PseudoKV` I've changed the issue description, thanks 👍

**Comment by jkawamoto** [comment]
I haven't known that too. So, the minimum download data size is 64 bytes, while the minimum upload data size is 4MiB. Is that correct? Then, caching might not be necessary. It depends on how often users upload less than 64bytes files, though.

**Comment by lukechampine** [comment]
>So, the minimum download data size is 64 bytes, while the minimum upload data size is 4MiB

That is correct, yes.

**Comment by MeijeSibbel** [comment]
Migrated to https://github.com/lukechampine/us/issues/78.
