### ISSUE TITLE
ReadResponse: communication error: rejected for low paying host valid output 	

### ISSUE THREAD

**Issue by jkawamoto** [lukechampine/us#96]
The error comment says 
> ErrLowHostValidOutput is returned if the renter incorrectly updates the host valid proof output during a file contract revision.

but what does it mean? Is that a similar error to "FormContract: ReadResponse: consensus conflict: provided transaction set is standalone and invalid: transaction spends a nonexisting siacoin output"?

**Comment by lukechampine** [comment]
`ErrLowHostValidOutput` means "you didn't pay me enough." (The "valid output" is the output that the host will receive at the end of the contract if it submits a successful storage proof.) There are a lot of variables involved in calculating the payment, so sometimes the renter and host disagree about how much the host should be paid. `us` adds 5% to its payment calculations to mitigate this.

"transaction spends a nonexisting siacoin output" means that the renter is trying to pay with a "coin" that is not in the host's consensus set. This can happen if the host is not fully synced, but more commonly it happens when the renter pays using a coin that was created in a transaction that has not been confirmed on-chain yet. To mitigate this, the renter will include the "parent" transaction in its FormContract request, but there is still a possibility of failure (e.g. if the host and renter have very different transaction pools).

**Comment by jkawamoto** [comment]
Does it mean if we get `ErrLowHostValidOutput`, the host isn't happy about the payment `us` offers and won't accept contracts? So, we have to disable the host, don't we?

**Comment by lukechampine** [comment]
If you get `ErrLowHostValidOutput`, you can usually just increase the amount and then the host will accept it. Sometimes, this error occurs because the host increased their prices, in which case you should be able to call the Settings RPC to fetch the updated prices. If that doesn't work, you can always resort to modifying the `(Session).Write` source directly, i.e. something like:
```diff
-   price = price.MulFloat(1.05)
+   price = price.MulFloat(1.10)
```
You can determine how large the multiplier should be by looking at the exact values returned in the `ErrLowHostValidOutput` error.
I'm hesitant to expose this multiplier in the API, though, because it wouldn't fix the root of the problem. Automatically retrying with updated Settings is probably the best next step to take. Long term, perhaps there are changes we can make to RHP3 to reduce the likelihood of this sort of error.

**Comment by jkawamoto** [comment]
I'd be nice if it's handled in FormContract and RenewContract functions.

If this will be fixed with the next protocol, perhaps we need to disable the hosts for now.

**Comment by jkawamoto** [comment]
Does this issue https://gitlab.com/NebulousLabs/Sia/-/merge_requests/4738 relate to this?

**Comment by lukechampine** [comment]
Unlikely. That MR shouldn't affect how up-to-date the host's settings are.

**Comment by jkawamoto** [comment]
I see 😞

**Comment by MeijeSibbel** [comment]
If we get `ErrLowHostValidOutput` and have to retry with a slightly higher price that shouldn't be a problem right? I mean, if the contract holds data and we disable the host, we will end up having to pay for a new contract and egress. With the default being 5% overhead, can't we just set this to e.g. 20% or higher if necessary and not worry about it anymore?

**Comment by lukechampine** [comment]
Well, that creates an incentive problem -- if the host knows that the renter will automatically pay 20% more, why wouldn't the host always return `ErrLowHostValidOutput`? It's free money.

I suppose you could sidestep this by lowering your maximum price by 20% during host selection, and then always paying 20% more than the host charges. But that's pretty ugly, and all users would have to be aware of it.

To be honest there's a lot of laxity around price controls in general, though. Like, right now nothing prevents a host from jacking up their prices as soon as you connect to them. How do you check whether the host's prices are sane? If you limit it to "the values we initially scanned, plus 5% leeway" then the host will always charge 5% more. Worse, hosts have to adjust their prices to compensate for market fluctuations in SC, so if the renter wants to be fair, it needs to query the exchange rate from some third-party API before each connection! Maybe the best way to deal with this is to let the host charge whatever it wants, and then use that information when deciding whether to renew. ¯\\\_(ツ)\_/¯

**Comment by jkawamoto** [comment]
Does this error, which is reported in [#hosting](https://discordapp.com/channels/341359001797132308/341362900117487636/742035711695519800), relate to this issue?
> 2020/08/08 23:08:46.072885 errors.go:150: communication error: error with 93.105.187.121:38440: incoming RPCLoopEnter failed: incoming RPCLoopFormContract failed: rejected for including too few transaction fees

**Comment by lukechampine** [comment]
That's a separate issue: the host thinks the renter is not providing sufficient miner fees on the contract transaction.

The `us` miner fee calculation is fairly stupid: it multiplies the maximum recommended fee by 2KB. It's possible that this is insufficient for some contracts, in particular those that use many small inputs or those that depend on large unconfirmed transactions. How frequently are you seeing this error? If it's more than a rare occurrence, I'll investigate it.

**Comment by jkawamoto** [comment]
We haven't seen the error.
Since the above error is reported by the other guy on Discord, I'm also not sure which the renter uses `us` or `siad`. 

But, perhaps, that isn't an issue for us.

**Comment by MeijeSibbel** [comment]
Chris:

> Unfortunately it still happens sometimes which is why in RHP3 we have the renter and host agree upon dynamic things like the blockheight and fees beforehand. That way we don't need to play that guessing game anymore.

**Comment by MeijeSibbel** [comment]
![image](https://user-images.githubusercontent.com/11735738/91640331-0231f100-ea1d-11ea-90d6-ba8121bd29c2.png)

We changed ` price = price.MulFloat(1.05)` to ` price = price.MulFloat(1.15)` but we get about the same number of errors in our logs... Would it be that there is some big contract renewal calculation error somewhere?

**Comment by lukechampine** [comment]
Sorry, to clarify, the 5% adjustment is only applied to the `Write` RPC, which you can only call after you've formed a contract. Since you're getting this error in `FormContract`, there must be a different cause.

The host will only return `ErrLowHostValidOutput` from `FormContract` if its valid output is less than its contract price. The renter sets the valid output to `contract price + collateral`, so the host should only return this error if the renter thinks the host's contract price is lower than the host does.

The `RenewContract` calculation is more complicated, but I don't see any discrepancies that would cause `ErrLowHostValidOutput` except for a differing contract price.

Is it possible your host settings are outdated? Can you print them out in the event of an error, and compare them to the settings reported on siastats?

**Comment by lukechampine** [comment]
Hmm, I just discovered that the host updates its contract price fairly often: it adjusts it based on the current recommended transaction fee. The host also recomputes its settings in just about every RPC call, so the contract price could definitely change between requesting the host's settings and using them.

I think the best short-term solution for this is to just add some leeway to the contract price, like we do in the `Write` RPC. I'll make a PR for this soon.

**Comment by lukechampine** [comment]
Okay, try running with #116 and see if the error persists.

**Comment by MeijeSibbel** [comment]
I don't know if this is relevant to this discussion but this contract list from a host (<https://siastats.info/hosts?=93>) [contracts.txt](https://github.com/lukechampine/us/files/5146938/contracts.txt) shows that the transaction fees can practically double within a single block;

```
b7a0e968f56180d48e3772a8a22a5cf5303a0cafb59630eaadaedf9652cb745c    Succeeded            1 SC             36.3 SC              11.18 SC             6.475 SC             258866               79.23 mS
b107937c6f2ed4e86b420086428c24db15d03894780db6aa1059f01473d644b0    Succeeded            1 SC             17.2 SC              14.5 SC              8.383 SC             258866               39 mS
```
Are we sure that 5% leeway is enough?

**Comment by lukechampine** [comment]
I don't have a ton of confidence in that number, but I suppose we can easily adjust as needed. It would help if we had some data showing how the recommended transaction fee changes over time. SiaStats has a graph of fees per transaction, but not fees per byte, which is what we're more interested in. The fees per transaction seem *reasonably* flat though, so I think 5% is at least in the right ballpark.

**Comment by jkawamoto** [comment]
Unfortunately, it looks like #116 doesn't fix this issue: 
![kibana](https://user-images.githubusercontent.com/1793096/91694110-1cadbc80-eb3a-11ea-91ff-867c49c1a37c.png)

**Comment by lukechampine** [comment]
Hmm. I also realized that my understanding of the contract price was not quite accurate. The host incorporates the transaction fee, but it actually uses the *maximum* of `MinContractPrice` and `(maximum fee) * (estimated txn size)`. So if fees are low (or contract price is high), there won't be any variation in the reported contract price between calls.

Still, just to be sure, I recommend that you try increasing the 5% to something much higher, like 50% or 100%. Contract prices are fairly low so this shouldn't affect total price very much. I also recommend printing out the host settings you're using to form the contract, so we can see if there's any discrepancy with the host's current settings.

**Comment by jkawamoto** [comment]
Since this error happens with both FormContract and RenewContract, I edited the title.

**Comment by jkawamoto** [comment]
@lukechampine So, which lines do we need to modify? 

https://github.com/lukechampine/us/blob/6837aef7ae837aba86f0345e0aac038b757e7bd6/renter/proto/renew.go#L83

https://github.com/lukechampine/us/blob/6837aef7ae837aba86f0345e0aac038b757e7bd6/renter/proto/formcontract.go#L87 

These lines?

**Comment by lukechampine** [comment]
yes, I recommend increasing those to `1.5` or `2`, at least temporarily, to see if the problem persists. Also, print out the settings in the event of a failure:

```diff
diff --git a/renter/proto/formcontract.go b/renter/proto/formcontract.go
index 212fc72..ebaf664 100644
--- a/renter/proto/formcontract.go
+++ b/renter/proto/formcontract.go
@@ -2,6 +2,8 @@ package proto
 
 import (
        "crypto/ed25519"
+       "encoding/json"
+       "fmt"
        "math/big"
        "reflect"
        "time"
@@ -217,6 +219,8 @@ func (s *Session) FormContract(w Wallet, tpool TransactionPool, key ed25519.Priv
        // Read the host signatures.
        var hostSigs renterhost.RPCFormContractSignatures
        if err := s.sess.ReadResponse(&hostSigs, 4096); err != nil {
+               settings, _ := json.Marshal(s.host)
+               fmt.Printf("host settings: %s\n", settings)
                return ContractRevision{}, nil, err
        }
        txn.TransactionSignatures = append(txn.TransactionSignatures, hostSigs.ContractSignatures...)
```

**Comment by jkawamoto** [comment]
The number of errors looks reduced but still get "rejected for low paying host valid output". I'll try with 2.0.

![kibana](https://user-images.githubusercontent.com/1793096/91779619-2da31000-ebc4-11ea-9282-0bb5a611dc38.png)

**Comment by jkawamoto** [comment]
Unfortunately, it looks like there is no difference even we pay 100% more (i.e. `s.host.ContractPrice.MulFloat(2.0)`). We still get many "rejected for low paying host valid output".

**Comment by jkawamoto** [comment]
We still get this error with #119 😞
![kibana](https://user-images.githubusercontent.com/1793096/92075937-7fe05e80-ed87-11ea-8cdc-a4431f15dfe1.png)

**Comment by jkawamoto** [comment]
Looks like #120 fixes this issue. I'll close this.
